#!/bin/bash
# Deploys this repo to production (webserver -> https://abofonsa.com) and verifies the result.
# Run it by hand from a clean checkout of the commit you want live:
#
#   ./deploy/deploy.sh                 # build+push image, ship config, restart, verify
#   ./deploy/deploy.sh --skip-build    # redeploy an already-pushed TAG (e.g. a rollback)
#   ./deploy/deploy.sh --verify-only   # touch nothing, just run the health/HTTP checks
#   TAG=a1b2c3d ./deploy/deploy.sh --skip-build   # roll back to a previous image
#   ./deploy/deploy.sh --yes           # non-interactive; skips the prompts (NOT the certbot one)
#
# Two channels decide where the image comes from (--channel, default 'private'):
#
#   private   built here by ./build.sh and pushed to docker.jojoaddison.net. Needs a JDK 21 and a
#             `docker login docker.jojoaddison.net` on this machine.
#   github    built by .github/workflows/publish.yml on a GitHub runner and pulled from
#             ghcr.io/<owner>/abofonsa-preview. Nothing is built locally, so this script confirms
#             the tag really is published before it touches the server.
#
#   ./deploy/deploy.sh --channel github               # deploy this commit's GHCR image
#   TAG=a1b2c3d ./deploy/deploy.sh --channel github   # roll back to any published tag
#
# Switching channels rewrites REGISTRY in the server's .env — after showing you the change — so the
# same commit can be served from either registry without editing anything on the host by hand.
#
#   ./deploy/deploy.sh --recover       # stack is running but its compose.yml/.env went missing
#   ./deploy/deploy.sh --bootstrap     # FIRST-TIME INSTALL on a server with nothing deployed
#   ./deploy/deploy.sh --bootstrap --with-nginx        # ... and install the host nginx site
#   ./deploy/deploy.sh --bootstrap --with-nginx --with-tls   # ... and run certbot for the domain
#
# What it does, in order: preflight -> [bootstrap: create dirs/networks/.env, ship config] ->
# build+push (build.sh) -> sync compose.yml -> point the server's .env at the new TAG -> pull +
# recreate -> wait for the app to report healthy -> [bootstrap: nginx + TLS] -> verify internally
# and publicly. Every mutating step is announced before it runs, and the irreversible-ish ones
# prompt unless --yes is passed.
#
# All four secrets this app needs (JWT_BASE64_SECRET, ABOFONSA_ADMIN_PASSWORD, ABOFONSA_HASH_SALT,
# POSTGRES_PASSWORD) are generated by `openssl rand` running ON THE SERVER during bootstrap, so they
# never exist on the deploying machine, in its shell history, or on the wire.
set -euo pipefail

# Resolved before the cd below, because --help reads this file back with sed. Relying on $0 after
# changing directory breaks the moment the script is invoked by a relative path that was relative to
# somewhere else — `./deploy/deploy.sh --help` being the obvious one.
SCRIPT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$(basename "${BASH_SOURCE[0]}")"

cd "$(dirname "${BASH_SOURCE[0]}")"

# --- Configuration -----------------------------------------------------------------------------

SSH_HOST="${SSH_HOST:-webserver}"                                        # ~/.ssh/config alias
REMOTE_DIR="${REMOTE_DIR:-~/webroot/01-healthconnect/abofonsa-preview}"  # expanded remotely, not here
PUBLIC_URL="${PUBLIC_URL:-https://abofonsa.com}"
# Extra hostnames served by the same nginx block and covered by the same certificate.
# Must match `server_name` in prod-server/abofonsa-preview.conf.
ALT_HOSTS="${ALT_HOSTS:-www.abofonsa.com}"
APP_PORT="${APP_PORT:-8084}"   # loopback-only port the host nginx proxies to
# Must match `container_name:` in prod-server/compose.yml. Hyphens, not underscores: an underscore
# is illegal in a hostname, so a container named abofonsa_preview_app cannot be addressed over the
# compose network without Tomcat rejecting the request with a bare 400.
APP_CONTAINER="abofonsa-preview-app"
DB_CONTAINER="abofonsa-preview-postgres"
APP_NETWORK="abofonsapreviewnet"
NGINX_CONF="abofonsa-preview.conf"
NGINX_HEADERS="abofonsa-security-headers.conf"   # included by the site file; must be installed with it

# Liquibase runs 19 changelogs and the metrics rollup backfills on startup, on a single-core host.
# This is expected, not a hang — see prod-server/compose.yml's healthcheck comment.
HEALTH_TIMEOUT_SECS="${HEALTH_TIMEOUT_SECS:-600}"
HEALTH_POLL_SECS=10

# Where each channel's image lives. Both are namespaces, not bare hosts: GHCR addresses images as
# ghcr.io/<owner>/<image>, and compose.yml interpolates "${REGISTRY}/abofonsa-preview:${TAG}"
# either way, so nothing downstream needs to know which channel produced the image.
#
# The GHCR owner is the account the repository lives under: origin is github.com:kojoampia/
# hc-abofonsa, the same namespace as the sibling hc-crowdfund-app. Hard-coded rather than parsed out
# of `git remote` so a clone with a differently-named remote still deploys the same image;
# GITHUB_REGISTRY overrides it for a fork or an organisation.
PRIVATE_REGISTRY="${PRIVATE_REGISTRY:-docker.jojoaddison.net}"
GITHUB_REGISTRY="${GITHUB_REGISTRY:-ghcr.io/kojoampia}"

# --- Argument parsing --------------------------------------------------------------------------

SKIP_BUILD=false
VERIFY_ONLY=false
ASSUME_YES=false
BOOTSTRAP=false
RECOVER=false
WITH_NGINX=false
WITH_TLS=false
CHANNEL="${CHANNEL:-private}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --skip-build)  SKIP_BUILD=true ;;
    --verify-only) VERIFY_ONLY=true; SKIP_BUILD=true ;;
    --yes|-y)      ASSUME_YES=true ;;
    --bootstrap)   BOOTSTRAP=true ;;
    --recover)     RECOVER=true; SKIP_BUILD=true ;;
    --with-nginx)  WITH_NGINX=true ;;
    --with-tls)    WITH_TLS=true; WITH_NGINX=true ;;
    --channel)     shift; CHANNEL="${1:-}"; [[ -n "$CHANNEL" ]] || { echo "--channel needs a value: private|github" >&2; exit 2; } ;;
    --channel=*)   CHANNEL="${1#--channel=}" ;;
    --github)      CHANNEL=github ;;   # shorthand for --channel github
    # Prints the header block, stopping at `set -euo pipefail`. A fixed line range goes stale the
    # first time the header grows — which is how --help ends up truncating the flag it documents.
    -h|--help)     awk 'NR > 1 { if ($0 ~ /^set -euo pipefail/) exit; sub(/^# ?/, ""); print }' "$SCRIPT_PATH"; exit 0 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
  shift
done

case "$CHANNEL" in
  private)
    REGISTRY="${REGISTRY:-$PRIVATE_REGISTRY}"
    ;;
  github)
    REGISTRY="${REGISTRY:-$GITHUB_REGISTRY}"
    # The whole point of this channel is that GitHub Actions did the building. Never fall through
    # to build.sh here — that would push a locally built image over the one Actions published,
    # under the same tag, which is exactly the drift the channel exists to prevent. The build step
    # checks the tag really is published instead.
    SKIP_BUILD=true
    ;;
  *) echo "unknown channel: $CHANNEL (expected 'private' or 'github')" >&2; exit 2 ;;
esac

# --verify-only inspects what is already running and deploys nothing, so there is no tag to check.
GITHUB_CHANNEL_VERIFY=false
if [[ "$CHANNEL" == "github" ]] && ! $VERIFY_ONLY; then
  GITHUB_CHANNEL_VERIFY=true
fi

# Threaded through the rollback and re-run hints, so a copy-pasted command stays on this channel.
CHANNEL_FLAG=""
[[ "$CHANNEL" == "private" ]] || CHANNEL_FLAG="--channel $CHANNEL "

# Domain for the nginx site and certbot, derived from PUBLIC_URL (https://host -> host).
PUBLIC_HOST="${PUBLIC_URL#https://}"; PUBLIC_HOST="${PUBLIC_HOST#http://}"; PUBLIC_HOST="${PUBLIC_HOST%%/*}"

TAG="${TAG:-$(git rev-parse --short HEAD)}"

# --- Output helpers ------------------------------------------------------------------------------

bold=$'\033[1m'; red=$'\033[31m'; green=$'\033[32m'; yellow=$'\033[33m'; reset=$'\033[0m'
step()  { echo "${bold}==> $*${reset}"; }
info()  { echo "    $*"; }
ok()    { echo "    ${green}ok${reset}  $*"; }
warn()  { echo "    ${yellow}warn${reset} $*" >&2; }
fail()  { echo "${red}FAILED${reset} $*" >&2; exit 1; }

confirm() {
  $ASSUME_YES && return 0
  local reply
  read -r -p "    $1 [y/N] " reply
  [[ "$reply" == "y" || "$reply" == "Y" ]]
}

remote() { ssh "$SSH_HOST" "$@"; }

# --- Preflight -----------------------------------------------------------------------------------

step "Preflight"

command -v ssh >/dev/null || fail "ssh not found"
command -v docker >/dev/null || fail "docker not found"

ssh -o BatchMode=yes -o ConnectTimeout=10 "$SSH_HOST" true 2>/dev/null \
  || fail "cannot ssh to '$SSH_HOST' non-interactively. Check ~/.ssh/config and your agent."
ok "ssh to $SSH_HOST"

remote "command -v docker >/dev/null" || fail "docker not installed on $SSH_HOST"
ok "docker on $SSH_HOST"

# A deploy from a dirty tree produces an image tagged with a commit that does not describe it. That
# is not fatal, but it makes "what is deployed" unanswerable, so say so out loud. Only meaningful on
# the private channel, where this working tree is what gets built.
if [[ "$CHANNEL" == "private" ]] && [[ -n "$(git status --porcelain)" ]] && ! $VERIFY_ONLY; then
  warn "working tree is dirty — image ${TAG} will not match commit ${TAG}"
  confirm "continue anyway?" || fail "aborted"
fi

# On the github channel the image comes from a commit GitHub has, not from this working tree, so
# what matters is that HEAD was actually pushed: an unpushed commit means Actions never saw it and
# the tag cannot exist. Local edits are harmless here rather than misleading — they simply are not
# in the image — so this warns and does not prompt.
if $GITHUB_CHANNEL_VERIFY; then
  if [[ -n "$(git status --porcelain --untracked-files=no)" ]]; then
    warn "working tree has uncommitted changes — they are NOT in image ${TAG} (Actions built commit ${TAG})"
  fi
  if git branch -r --contains HEAD 2>/dev/null | grep -q .; then
    ok "commit ${TAG} is on a remote branch (the publish workflow could have built it)"
  else
    warn "commit ${TAG} is not on any remote branch — push it so .github/workflows/publish.yml runs"
  fi

  # The *server* does the pulling, and it is a different machine with its own credential store.
  # A GHCR package is private by default, and a private package needs a login on the host — not
  # here. Checked now rather than discovered from a failed pull with the stack already stopped.
  if remote "grep -q ghcr.io ~/.docker/config.json 2>/dev/null"; then
    ok "${SSH_HOST} has a stored ghcr.io credential"
  else
    warn "${SSH_HOST} has no stored ghcr.io credential. That is fine only if the package is public"
    warn "(Packages -> abofonsa-preview -> Package settings -> Change visibility). Otherwise run:"
    warn "  ssh ${SSH_HOST} 'docker login ghcr.io -u <user>'   # a PAT with read:packages"
  fi
fi

info "tag:        ${TAG}"
info "channel:    ${CHANNEL} (${REGISTRY})"
info "remote dir: ${REMOTE_DIR}"
info "public url: ${PUBLIC_URL}"

# --- Bootstrap: first-time install ----------------------------------------------------------------

if $BOOTSTRAP; then
  step "Bootstrap"

  if remote "test -f ${REMOTE_DIR}/compose.yml"; then
    fail "${REMOTE_DIR}/compose.yml already exists — this looks like an existing install.
       Use a normal deploy, or --recover if the config went missing."
  fi

  confirm "create ${REMOTE_DIR} on ${SSH_HOST} and generate secrets there?" || fail "aborted"

  remote "mkdir -p ${REMOTE_DIR}"
  ok "created ${REMOTE_DIR}"

  scp -q prod-server/infra.sh "${SSH_HOST}:${REMOTE_DIR}/infra.sh"
  remote "chmod +x ${REMOTE_DIR}/infra.sh && ${REMOTE_DIR}/infra.sh"
  ok "network ${APP_NETWORK}"

  # Secrets are generated remotely and written straight into .env. They are never echoed, never
  # travel over the wire, and never enter this machine's shell history. `set -o noclobber` style
  # guard: refuse if .env somehow exists, rather than overwrite a working one.
  remote "test ! -f ${REMOTE_DIR}/.env" || fail ".env already exists on the server; refusing to overwrite it"

  remote "umask 077 && cat > ${REMOTE_DIR}/.env <<EOF
REGISTRY=${REGISTRY}
TAG=${TAG}
POSTGRES_PASSWORD=\$(openssl rand -base64 24 | tr -d '\n')
JWT_BASE64_SECRET=\$(openssl rand -base64 64 | tr -d '\n')
ABOFONSA_ADMIN_PASSWORD=\$(openssl rand -base64 24 | tr -d '\n')
ABOFONSA_HASH_SALT=\$(openssl rand -base64 32 | tr -d '\n')
PUBLIC_URL=${PUBLIC_URL}
APP_PORT=${APP_PORT}
WAITLIST_MAX_PER_HOUR=5
SMTP_HOST=
SMTP_PORT=587
SMTP_USERNAME=
SMTP_PASSWORD=
SMTP_AUTH=true
SMTP_STARTTLS=true
MAIL_FROM=noreply@${PUBLIC_HOST#*.}
EOF
chmod 600 ${REMOTE_DIR}/.env"
  ok "generated .env with four fresh secrets (chmod 600)"

  warn "mail is not configured. Until SMTP_HOST is set in ${REMOTE_DIR}/.env, confirmation links"
  warn "are written to the log instead of sent, so nobody outside the server can confirm a signup."
  warn "Read the admin password with:  ssh ${SSH_HOST} \"grep ABOFONSA_ADMIN_PASSWORD ${REMOTE_DIR}/.env\""
fi

# --- Recover: config went missing on a running stack -----------------------------------------------

if $RECOVER; then
  step "Recover"
  remote "test -f ${REMOTE_DIR}/.env" \
    || fail "${REMOTE_DIR}/.env is missing too — recovery cannot invent the secrets. Restore it from
       your password manager, or re-bootstrap into a fresh directory and restore the database."
  ok ".env is present; only compose.yml and helpers will be re-shipped"
fi

# --- Build and push --------------------------------------------------------------------------------

if ! $SKIP_BUILD; then
  step "Build and push ${REGISTRY}/abofonsa-preview:${TAG}"
  TAG="$TAG" REGISTRY="$REGISTRY" ./build.sh
  ok "image pushed"
elif $GITHUB_CHANNEL_VERIFY; then
  # Nothing is built here; GitHub Actions did that. Confirm the image exists under this tag before
  # restarting anything — the alternative is finding out from a failed `pull` with the stack
  # already stopped.
  step "Check ${TAG} is published to ${REGISTRY}"
  info "Published by .github/workflows/publish.yml — see the repository's Actions tab if this fails."

  if docker manifest inspect "${REGISTRY}/abofonsa-preview:${TAG}" >/dev/null 2>&1; then
    ok "${REGISTRY}/abofonsa-preview:${TAG} exists"
  else
    # A warning rather than a hard stop: this same lookup fails for a package that is published but
    # private, and nothing on this machine is necessarily logged in to ghcr.io. Refusing to deploy
    # on that basis would block a perfectly good private-package setup.
    warn "cannot see ${REGISTRY}/abofonsa-preview:${TAG}. Either the workflow has not published it"
    warn "yet, or the package is private and this machine is not logged in:"
    warn "  docker login ${REGISTRY%%/*} -u <user>   # a PAT with read:packages"
    confirm "continue and let the server try to pull it?" || fail "aborted"
  fi
else
  $VERIFY_ONLY || info "skipping build; deploying existing tag ${TAG}"
fi

# --- Ship configuration -----------------------------------------------------------------------------

if ! $VERIFY_ONLY; then
  step "Ship configuration"

  # The files in this repository are the source of truth, not a starting point to be edited on the
  # server. A change made only on the host is lost at the next deploy and invisible to review.
  scp -q prod-server/compose.yml "${SSH_HOST}:${REMOTE_DIR}/compose.yml"
  scp -q prod-server/start       "${SSH_HOST}:${REMOTE_DIR}/start"
  scp -q prod-server/backup.sh   "${SSH_HOST}:${REMOTE_DIR}/backup.sh"
  scp -q prod-server/infra.sh    "${SSH_HOST}:${REMOTE_DIR}/infra.sh"
  remote "chmod +x ${REMOTE_DIR}/start ${REMOTE_DIR}/backup.sh ${REMOTE_DIR}/infra.sh"
  ok "compose.yml, start, backup.sh, infra.sh"

  # Point .env at the registry and tag being deployed. sed in place rather than rewriting the file,
  # because it holds secrets this script must never read, let alone reconstruct.
  #
  # REGISTRY first, and always — compose.yml reads "${REGISTRY}/abofonsa-preview:${TAG}", so
  # switching channels is exactly this one line changing. Leave it stale and the pull below quietly
  # fetches the other channel's image at the new tag, or fails because that registry never had it.
  # `|` as the sed delimiter, not `/`: a GHCR namespace contains a slash.
  #
  # An .env predating this key would otherwise fall through to compose.yml's own default, which is
  # the private registry — silently ignoring --channel github.
  remote_registry="$(remote "grep -m1 '^REGISTRY=' ${REMOTE_DIR}/.env | cut -d= -f2-" || true)"
  if [[ "$remote_registry" == "$REGISTRY" ]]; then
    ok "REGISTRY=${REGISTRY} already set in .env (${CHANNEL} channel)"
  else
    info "the server pulls from ${remote_registry:-<unset>}; this deploy uses ${REGISTRY}"
    confirm "switch the server's REGISTRY to ${REGISTRY}?" || fail "aborted"
    remote "grep -q '^REGISTRY=' ${REMOTE_DIR}/.env \
      && sed -i 's|^REGISTRY=.*|REGISTRY=${REGISTRY}|' ${REMOTE_DIR}/.env \
      || echo 'REGISTRY=${REGISTRY}' >> ${REMOTE_DIR}/.env"
    ok "REGISTRY: ${remote_registry:-<unset>} -> ${REGISTRY}"
  fi

  remote "grep -q '^TAG=' ${REMOTE_DIR}/.env \
    && sed -i 's|^TAG=.*|TAG=${TAG}|' ${REMOTE_DIR}/.env \
    || echo 'TAG=${TAG}' >> ${REMOTE_DIR}/.env"
  ok "TAG=${TAG} in .env"
fi

# --- Restart ------------------------------------------------------------------------------------------

if ! $VERIFY_ONLY; then
  step "Restart the stack"
  confirm "pull ${TAG} and recreate containers on ${SSH_HOST}?" || fail "aborted"
  remote "cd ${REMOTE_DIR} && ./start"
  ok "containers recreated"
fi

# --- Wait for health -------------------------------------------------------------------------------

step "Wait for health (up to ${HEALTH_TIMEOUT_SECS}s)"
info "Liquibase and the rollup backfill run at startup; minutes, not seconds, is normal here."

deadline=$(( SECONDS + HEALTH_TIMEOUT_SECS ))
healthy=false
while (( SECONDS < deadline )); do
  status="$(remote "docker inspect -f '{{.State.Health.Status}}' ${APP_CONTAINER} 2>/dev/null" || echo "missing")"
  case "$status" in
    healthy) healthy=true; break ;;
    missing) warn "container ${APP_CONTAINER} not found yet" ;;
    *)       info "health: ${status}" ;;
  esac
  sleep "$HEALTH_POLL_SECS"
done

if ! $healthy; then
  echo "" >&2
  warn "still not healthy after ${HEALTH_TIMEOUT_SECS}s. Last 60 log lines:"
  remote "docker logs --tail 60 ${APP_CONTAINER} 2>&1" >&2 || true
  fail "app did not become healthy"
fi
ok "${APP_CONTAINER} is healthy"

# --- nginx and TLS -------------------------------------------------------------------------------------

if $WITH_NGINX; then
  step "Install the nginx site"
  confirm "install /etc/nginx/sites-available/${NGINX_CONF} on ${SSH_HOST} (needs sudo)?" || fail "aborted"

  # The site file `include`s the headers snippet, so that has to land first or `nginx -t` fails.
  scp -q "prod-server/${NGINX_HEADERS}" "${SSH_HOST}:/tmp/${NGINX_HEADERS}"
  remote "sudo install -D -m 0644 -o root -g root /tmp/${NGINX_HEADERS} /etc/nginx/snippets/${NGINX_HEADERS} \
       && rm -f /tmp/${NGINX_HEADERS}"
  ok "security headers snippet installed"

  scp -q "prod-server/${NGINX_CONF}" "${SSH_HOST}:/tmp/${NGINX_CONF}"
  remote "sudo mv /tmp/${NGINX_CONF} /etc/nginx/sites-available/${NGINX_CONF} \
       && sudo ln -sf /etc/nginx/sites-available/${NGINX_CONF} /etc/nginx/sites-enabled/${NGINX_CONF} \
       && sudo nginx -t"
  ok "nginx config valid"
  remote "sudo systemctl reload nginx"
  ok "nginx reloaded"
fi

if $WITH_TLS; then
  step "TLS via certbot"

  CERT_HOSTS="$PUBLIC_HOST $ALT_HOSTS"
  CERT_ARGS=()
  for h in $CERT_HOSTS; do CERT_ARGS+=(-d "$h"); done

  # DNS is checked programmatically rather than trusted. Let's Encrypt validates by resolving the
  # name and fetching from it, so a host that does not point here cannot possibly pass — and a
  # failed validation still consumes rate-limit quota. Better to refuse than to spend it.
  SERVER_IP="$(remote "curl -sf -m 10 https://api.ipify.org || hostname -I | awk '{print \$1}'")"
  for h in $CERT_HOSTS; do
    resolved="$(getent hosts "$h" | awk '{print $1}' | head -1)"
    if [[ -z "$resolved" ]]; then
      fail "$h has no DNS record. Point it at $SERVER_IP before requesting a certificate."
    elif [[ "$resolved" != "$SERVER_IP" ]]; then
      fail "$h resolves to $resolved, not $SERVER_IP. Certbot would fail and burn rate-limit quota."
    fi
    ok "dns       $h -> $resolved"
  done

  if remote "test -d /etc/letsencrypt/live/$PUBLIC_HOST"; then
    info "a certificate for $PUBLIC_HOST already exists; certbot will reuse or expand it"
  fi

  # --yes covers this step. The earlier version always prompted, on the reasoning that certbot talks
  # to a rate-limited third party about a real domain — but a `read` in a non-interactive shell gets
  # EOF and silently skips, which turns an explicit --with-tls into a no-op. The DNS checks above are
  # a stronger guard than a prompt anyway: they verify the precondition the prompt was asking a human
  # to vouch for.
  if $ASSUME_YES; then
    info "requesting a certificate for: $CERT_HOSTS"
    remote "sudo certbot --nginx ${CERT_ARGS[*]} --non-interactive --agree-tos --keep-until-expiring --redirect"
    ok "certificate issued and nginx rewritten"
  else
    echo ""
    warn "certbot rewrites ${NGINX_CONF} in place and requests a real certificate from Let's Encrypt."
    warn "Rate limits apply per domain, and this is not a step to repeat casually."
    echo ""
    read -r -p "    run: certbot --nginx ${CERT_ARGS[*]} ? [y/N] " reply
    if [[ "$reply" == "y" || "$reply" == "Y" ]]; then
      remote "sudo certbot --nginx ${CERT_ARGS[*]} --agree-tos --keep-until-expiring --redirect"
      ok "certificate issued and nginx rewritten"
    else
      info "skipped; run it by hand when DNS is ready"
    fi
  fi
fi

# --- Verify --------------------------------------------------------------------------------------------

step "Verify"

# Which image is actually running. The same tag can exist in both registries, so the published-tag
# check above would pass while the container still ran the other channel's image — only this says
# the REGISTRY switch reached the container. Skipped for --verify-only, which reports on whatever is
# live rather than on a channel someone asked for.
running_image="$(remote "docker inspect ${APP_CONTAINER} --format '{{.Config.Image}}'" 2>/dev/null || echo "")"
info "image:    ${running_image:-<unknown>}"
if ! $VERIFY_ONLY; then
  if [[ "$running_image" == "${REGISTRY}/"*":${TAG}" ]]; then
    ok "running  ${TAG} from ${REGISTRY} (${CHANNEL} channel)"
  else
    warn "expected ${REGISTRY}/abofonsa-preview:${TAG} — the .env change may not have been applied"
  fi
fi

# Internal: straight at the container's loopback port, bypassing nginx. Distinguishes "the app is
# broken" from "the proxy is misconfigured", which look identical from outside.
internal_health="$(remote "curl -sf -m 10 http://127.0.0.1:${APP_PORT}/management/health" || echo "")"
if [[ "$internal_health" == *'"status":"UP"'* ]]; then
  ok "internal  /management/health is UP"
else
  fail "internal health check failed at 127.0.0.1:${APP_PORT}"
fi

internal_content="$(remote "curl -sf -m 15 http://127.0.0.1:${APP_PORT}/api/public/content" || echo "")"
if [[ "$internal_content" == *'"launchAt"'* ]]; then
  ok "internal  /api/public/content serves the launch payload"
else
  fail "internal /api/public/content did not return a launch payload — check the Liquibase seed"
fi

# The seeds carry contextFilter="!test"; if they had been skipped the page would render empty, which
# is the kind of thing that looks fine in a health check and wrong to every visitor.
service_count="$(remote "curl -sf -m 15 http://127.0.0.1:${APP_PORT}/api/public/content | grep -o 'slug' | wc -l" || echo 0)"
if [[ "$service_count" -ge 1 ]]; then
  ok "internal  content has ${service_count} seeded service(s)"
else
  warn "content payload has no services — the content seed did not run in this environment"
fi

# The admin surface must not be anonymous. Checked every deploy because it is exactly the kind of
# thing a security-config edit breaks silently.
admin_code="$(remote "curl -s -o /dev/null -w '%{http_code}' -m 10 http://127.0.0.1:${APP_PORT}/api/admin/metrics/summary" || echo "000")"
if [[ "$admin_code" == "401" ]]; then
  ok "internal  /api/admin/** rejects anonymous callers (401)"
else
  fail "/api/admin/metrics/summary answered ${admin_code} to an anonymous request — expected 401"
fi

register_code="$(remote "curl -s -o /dev/null -w '%{http_code}' -m 10 -X POST -H 'Content-Type: application/json' -d '{}' http://127.0.0.1:${APP_PORT}/api/register" || echo "000")"
if [[ "$register_code" == "401" || "$register_code" == "403" || "$register_code" == "404" ]]; then
  ok "internal  public registration is closed (${register_code})"
else
  warn "/api/register answered ${register_code} — expected it to be closed"
fi

# Public: through nginx and TLS, from this machine. Skipped when the site is not published yet.
if curl -sf -m 15 -o /dev/null "${PUBLIC_URL}/management/health" 2>/dev/null; then
  ok "public    ${PUBLIC_URL}/management/health reachable"
elif curl -sf -m 15 -o /dev/null "${PUBLIC_URL}" 2>/dev/null; then
  ok "public    ${PUBLIC_URL} reachable (management is 404 by design at the proxy)"
else
  warn "public    ${PUBLIC_URL} not reachable from here — expected until DNS and TLS are in place"
fi

echo ""
step "Deployed ${TAG}"
info "public:   ${PUBLIC_URL}"
info "channel:  ${CHANNEL} (${REGISTRY})"
info "logs:     ssh ${SSH_HOST} 'docker logs -f ${APP_CONTAINER}'"
info "psql:     ssh ${SSH_HOST} 'docker exec -it ${DB_CONTAINER} psql -U abofonsaPreview -d abofonsaPreview'"
info "rollback: TAG=<previous-sha> ./deploy/deploy.sh ${CHANNEL_FLAG}--skip-build"
