package net.jojoaddison.abofonsa.preview.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CaptureEventAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCaptureEventAllPropertiesEquals(CaptureEvent expected, CaptureEvent actual) {
        assertCaptureEventAutoGeneratedPropertiesEquals(expected, actual);
        assertCaptureEventAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCaptureEventAllUpdatablePropertiesEquals(CaptureEvent expected, CaptureEvent actual) {
        assertCaptureEventUpdatableFieldsEquals(expected, actual);
        assertCaptureEventUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCaptureEventAutoGeneratedPropertiesEquals(CaptureEvent expected, CaptureEvent actual) {
        assertThat(actual)
            .as("Verify CaptureEvent auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCaptureEventUpdatableFieldsEquals(CaptureEvent expected, CaptureEvent actual) {
        assertThat(actual)
            .as("Verify CaptureEvent relevant properties")
            .satisfies(a -> assertThat(a.getEventType()).as("check eventType").isEqualTo(expected.getEventType()))
            .satisfies(a -> assertThat(a.getOccurredAt()).as("check occurredAt").isEqualTo(expected.getOccurredAt()))
            .satisfies(a -> assertThat(a.getOccurredDate()).as("check occurredDate").isEqualTo(expected.getOccurredDate()))
            .satisfies(a -> assertThat(a.getSessionHash()).as("check sessionHash").isEqualTo(expected.getSessionHash()))
            .satisfies(a -> assertThat(a.getLocale()).as("check locale").isEqualTo(expected.getLocale()))
            .satisfies(a -> assertThat(a.getSourcePage()).as("check sourcePage").isEqualTo(expected.getSourcePage()))
            .satisfies(a -> assertThat(a.getUtmSource()).as("check utmSource").isEqualTo(expected.getUtmSource()))
            .satisfies(a -> assertThat(a.getUtmMedium()).as("check utmMedium").isEqualTo(expected.getUtmMedium()))
            .satisfies(a -> assertThat(a.getUtmCampaign()).as("check utmCampaign").isEqualTo(expected.getUtmCampaign()))
            .satisfies(a -> assertThat(a.getReferrerHost()).as("check referrerHost").isEqualTo(expected.getReferrerHost()))
            .satisfies(a -> assertThat(a.getDeviceType()).as("check deviceType").isEqualTo(expected.getDeviceType()))
            .satisfies(a -> assertThat(a.getCountryCode()).as("check countryCode").isEqualTo(expected.getCountryCode()))
            .satisfies(a -> assertThat(a.getTargetKey()).as("check targetKey").isEqualTo(expected.getTargetKey()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCaptureEventUpdatableRelationshipsEquals(CaptureEvent expected, CaptureEvent actual) {
        // empty method
    }
}
