package net.jojoaddison.abofonsa.preview.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CareServiceTeaserAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCareServiceTeaserAllPropertiesEquals(CareServiceTeaser expected, CareServiceTeaser actual) {
        assertCareServiceTeaserAutoGeneratedPropertiesEquals(expected, actual);
        assertCareServiceTeaserAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCareServiceTeaserAllUpdatablePropertiesEquals(CareServiceTeaser expected, CareServiceTeaser actual) {
        assertCareServiceTeaserUpdatableFieldsEquals(expected, actual);
        assertCareServiceTeaserUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCareServiceTeaserAutoGeneratedPropertiesEquals(CareServiceTeaser expected, CareServiceTeaser actual) {
        assertThat(actual)
            .as("Verify CareServiceTeaser auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCareServiceTeaserUpdatableFieldsEquals(CareServiceTeaser expected, CareServiceTeaser actual) {
        assertThat(actual)
            .as("Verify CareServiceTeaser relevant properties")
            .satisfies(a -> assertThat(a.getSlug()).as("check slug").isEqualTo(expected.getSlug()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getBlurb()).as("check blurb").isEqualTo(expected.getBlurb()))
            .satisfies(a -> assertThat(a.getIconKey()).as("check iconKey").isEqualTo(expected.getIconKey()))
            .satisfies(a -> assertThat(a.getAvailableOn()).as("check availableOn").isEqualTo(expected.getAvailableOn()))
            .satisfies(a -> assertThat(a.getDisplayOrder()).as("check displayOrder").isEqualTo(expected.getDisplayOrder()))
            .satisfies(a -> assertThat(a.getPublished()).as("check published").isEqualTo(expected.getPublished()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCareServiceTeaserUpdatableRelationshipsEquals(CareServiceTeaser expected, CareServiceTeaser actual) {
        // empty method
    }
}
