package net.jojoaddison.abofonsa.preview.domain;

import static net.jojoaddison.abofonsa.preview.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class CarePlanTeaserAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarePlanTeaserAllPropertiesEquals(CarePlanTeaser expected, CarePlanTeaser actual) {
        assertCarePlanTeaserAutoGeneratedPropertiesEquals(expected, actual);
        assertCarePlanTeaserAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarePlanTeaserAllUpdatablePropertiesEquals(CarePlanTeaser expected, CarePlanTeaser actual) {
        assertCarePlanTeaserUpdatableFieldsEquals(expected, actual);
        assertCarePlanTeaserUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarePlanTeaserAutoGeneratedPropertiesEquals(CarePlanTeaser expected, CarePlanTeaser actual) {
        assertThat(actual)
            .as("Verify CarePlanTeaser auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarePlanTeaserUpdatableFieldsEquals(CarePlanTeaser expected, CarePlanTeaser actual) {
        assertThat(actual)
            .as("Verify CarePlanTeaser relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getForWho()).as("check forWho").isEqualTo(expected.getForWho()))
            .satisfies(a ->
                assertThat(a.getPriceAmount())
                    .as("check priceAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getPriceAmount())
            )
            .satisfies(a -> assertThat(a.getPriceCurrency()).as("check priceCurrency").isEqualTo(expected.getPriceCurrency()))
            .satisfies(a -> assertThat(a.getPricePeriod()).as("check pricePeriod").isEqualTo(expected.getPricePeriod()))
            .satisfies(a -> assertThat(a.getPriceNote()).as("check priceNote").isEqualTo(expected.getPriceNote()))
            .satisfies(a -> assertThat(a.getFeatured()).as("check featured").isEqualTo(expected.getFeatured()))
            .satisfies(a -> assertThat(a.getDisplayOrder()).as("check displayOrder").isEqualTo(expected.getDisplayOrder()))
            .satisfies(a -> assertThat(a.getPublished()).as("check published").isEqualTo(expected.getPublished()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarePlanTeaserUpdatableRelationshipsEquals(CarePlanTeaser expected, CarePlanTeaser actual) {
        // empty method
    }
}
