package net.jojoaddison.abofonsa.preview.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DataExportLogAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDataExportLogAllPropertiesEquals(DataExportLog expected, DataExportLog actual) {
        assertDataExportLogAutoGeneratedPropertiesEquals(expected, actual);
        assertDataExportLogAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDataExportLogAllUpdatablePropertiesEquals(DataExportLog expected, DataExportLog actual) {
        assertDataExportLogUpdatableFieldsEquals(expected, actual);
        assertDataExportLogUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDataExportLogAutoGeneratedPropertiesEquals(DataExportLog expected, DataExportLog actual) {
        assertThat(actual)
            .as("Verify DataExportLog auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDataExportLogUpdatableFieldsEquals(DataExportLog expected, DataExportLog actual) {
        assertThat(actual)
            .as("Verify DataExportLog relevant properties")
            .satisfies(a -> assertThat(a.getExportKind()).as("check exportKind").isEqualTo(expected.getExportKind()))
            .satisfies(a -> assertThat(a.getFormat()).as("check format").isEqualTo(expected.getFormat()))
            .satisfies(a -> assertThat(a.getRangeFrom()).as("check rangeFrom").isEqualTo(expected.getRangeFrom()))
            .satisfies(a -> assertThat(a.getRangeTo()).as("check rangeTo").isEqualTo(expected.getRangeTo()))
            .satisfies(a -> assertThat(a.getBucketType()).as("check bucketType").isEqualTo(expected.getBucketType()))
            .satisfies(a -> assertThat(a.getFilterSummary()).as("check filterSummary").isEqualTo(expected.getFilterSummary()))
            .satisfies(a -> assertThat(a.getRowCount()).as("check rowCount").isEqualTo(expected.getRowCount()))
            .satisfies(a -> assertThat(a.getRequestedBy()).as("check requestedBy").isEqualTo(expected.getRequestedBy()))
            .satisfies(a -> assertThat(a.getRequestedAt()).as("check requestedAt").isEqualTo(expected.getRequestedAt()))
            .satisfies(a -> assertThat(a.getDurationMs()).as("check durationMs").isEqualTo(expected.getDurationMs()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDataExportLogUpdatableRelationshipsEquals(DataExportLog expected, DataExportLog actual) {
        // empty method
    }
}
