package net.jojoaddison.abofonsa.preview.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LaunchMilestoneAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLaunchMilestoneAllPropertiesEquals(LaunchMilestone expected, LaunchMilestone actual) {
        assertLaunchMilestoneAutoGeneratedPropertiesEquals(expected, actual);
        assertLaunchMilestoneAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLaunchMilestoneAllUpdatablePropertiesEquals(LaunchMilestone expected, LaunchMilestone actual) {
        assertLaunchMilestoneUpdatableFieldsEquals(expected, actual);
        assertLaunchMilestoneUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLaunchMilestoneAutoGeneratedPropertiesEquals(LaunchMilestone expected, LaunchMilestone actual) {
        assertThat(actual)
            .as("Verify LaunchMilestone auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLaunchMilestoneUpdatableFieldsEquals(LaunchMilestone expected, LaunchMilestone actual) {
        assertThat(actual)
            .as("Verify LaunchMilestone relevant properties")
            .satisfies(a -> assertThat(a.getPhaseLabel()).as("check phaseLabel").isEqualTo(expected.getPhaseLabel()))
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getBody()).as("check body").isEqualTo(expected.getBody()))
            .satisfies(a -> assertThat(a.getMilestoneDate()).as("check milestoneDate").isEqualTo(expected.getMilestoneDate()))
            .satisfies(a -> assertThat(a.getCurrent()).as("check current").isEqualTo(expected.getCurrent()))
            .satisfies(a -> assertThat(a.getDisplayOrder()).as("check displayOrder").isEqualTo(expected.getDisplayOrder()))
            .satisfies(a -> assertThat(a.getPublished()).as("check published").isEqualTo(expected.getPublished()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLaunchMilestoneUpdatableRelationshipsEquals(LaunchMilestone expected, LaunchMilestone actual) {
        // empty method
    }
}
