package net.jojoaddison.abofonsa.preview.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LaunchSettingAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLaunchSettingAllPropertiesEquals(LaunchSetting expected, LaunchSetting actual) {
        assertLaunchSettingAutoGeneratedPropertiesEquals(expected, actual);
        assertLaunchSettingAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLaunchSettingAllUpdatablePropertiesEquals(LaunchSetting expected, LaunchSetting actual) {
        assertLaunchSettingUpdatableFieldsEquals(expected, actual);
        assertLaunchSettingUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLaunchSettingAutoGeneratedPropertiesEquals(LaunchSetting expected, LaunchSetting actual) {
        assertThat(actual)
            .as("Verify LaunchSetting auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLaunchSettingUpdatableFieldsEquals(LaunchSetting expected, LaunchSetting actual) {
        assertThat(actual)
            .as("Verify LaunchSetting relevant properties")
            .satisfies(a -> assertThat(a.getSettingKey()).as("check settingKey").isEqualTo(expected.getSettingKey()))
            .satisfies(a -> assertThat(a.getOrganisationName()).as("check organisationName").isEqualTo(expected.getOrganisationName()))
            .satisfies(a -> assertThat(a.getTagline()).as("check tagline").isEqualTo(expected.getTagline()))
            .satisfies(a -> assertThat(a.getLaunchAt()).as("check launchAt").isEqualTo(expected.getLaunchAt()))
            .satisfies(a -> assertThat(a.getLaunchTimezone()).as("check launchTimezone").isEqualTo(expected.getLaunchTimezone()))
            .satisfies(a -> assertThat(a.getFundUrl()).as("check fundUrl").isEqualTo(expected.getFundUrl()))
            .satisfies(a -> assertThat(a.getContactEmail()).as("check contactEmail").isEqualTo(expected.getContactEmail()))
            .satisfies(a -> assertThat(a.getContactPhone()).as("check contactPhone").isEqualTo(expected.getContactPhone()))
            .satisfies(a -> assertThat(a.getOfficeAddress()).as("check officeAddress").isEqualTo(expected.getOfficeAddress()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLaunchSettingUpdatableRelationshipsEquals(LaunchSetting expected, LaunchSetting actual) {
        // empty method
    }
}
