package net.jojoaddison.abofonsa.preview.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MetricRollupAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetricRollupAllPropertiesEquals(MetricRollup expected, MetricRollup actual) {
        assertMetricRollupAutoGeneratedPropertiesEquals(expected, actual);
        assertMetricRollupAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetricRollupAllUpdatablePropertiesEquals(MetricRollup expected, MetricRollup actual) {
        assertMetricRollupUpdatableFieldsEquals(expected, actual);
        assertMetricRollupUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetricRollupAutoGeneratedPropertiesEquals(MetricRollup expected, MetricRollup actual) {
        assertThat(actual)
            .as("Verify MetricRollup auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetricRollupUpdatableFieldsEquals(MetricRollup expected, MetricRollup actual) {
        assertThat(actual)
            .as("Verify MetricRollup relevant properties")
            .satisfies(a -> assertThat(a.getMetricKey()).as("check metricKey").isEqualTo(expected.getMetricKey()))
            .satisfies(a -> assertThat(a.getBucketType()).as("check bucketType").isEqualTo(expected.getBucketType()))
            .satisfies(a -> assertThat(a.getBucketStart()).as("check bucketStart").isEqualTo(expected.getBucketStart()))
            .satisfies(a -> assertThat(a.getBucketEnd()).as("check bucketEnd").isEqualTo(expected.getBucketEnd()))
            .satisfies(a -> assertThat(a.getDimensionName()).as("check dimensionName").isEqualTo(expected.getDimensionName()))
            .satisfies(a -> assertThat(a.getDimensionValue()).as("check dimensionValue").isEqualTo(expected.getDimensionValue()))
            .satisfies(a -> assertThat(a.getValue()).as("check value").isEqualTo(expected.getValue()))
            .satisfies(a -> assertThat(a.getComputedAt()).as("check computedAt").isEqualTo(expected.getComputedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetricRollupUpdatableRelationshipsEquals(MetricRollup expected, MetricRollup actual) {
        // empty method
    }
}
