package net.jojoaddison.abofonsa.preview.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PledgeTierPerkAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPledgeTierPerkAllPropertiesEquals(PledgeTierPerk expected, PledgeTierPerk actual) {
        assertPledgeTierPerkAutoGeneratedPropertiesEquals(expected, actual);
        assertPledgeTierPerkAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPledgeTierPerkAllUpdatablePropertiesEquals(PledgeTierPerk expected, PledgeTierPerk actual) {
        assertPledgeTierPerkUpdatableFieldsEquals(expected, actual);
        assertPledgeTierPerkUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPledgeTierPerkAutoGeneratedPropertiesEquals(PledgeTierPerk expected, PledgeTierPerk actual) {
        assertThat(actual)
            .as("Verify PledgeTierPerk auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPledgeTierPerkUpdatableFieldsEquals(PledgeTierPerk expected, PledgeTierPerk actual) {
        assertThat(actual)
            .as("Verify PledgeTierPerk relevant properties")
            .satisfies(a -> assertThat(a.getLabel()).as("check label").isEqualTo(expected.getLabel()))
            .satisfies(a -> assertThat(a.getDisplayOrder()).as("check displayOrder").isEqualTo(expected.getDisplayOrder()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPledgeTierPerkUpdatableRelationshipsEquals(PledgeTierPerk expected, PledgeTierPerk actual) {
        assertThat(actual)
            .as("Verify PledgeTierPerk relationships")
            .satisfies(a -> assertThat(a.getTier()).as("check tier").isEqualTo(expected.getTier()));
    }
}
