package net.jojoaddison.abofonsa.preview.domain;

import static net.jojoaddison.abofonsa.preview.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class PledgeTierTeaserAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPledgeTierTeaserAllPropertiesEquals(PledgeTierTeaser expected, PledgeTierTeaser actual) {
        assertPledgeTierTeaserAutoGeneratedPropertiesEquals(expected, actual);
        assertPledgeTierTeaserAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPledgeTierTeaserAllUpdatablePropertiesEquals(PledgeTierTeaser expected, PledgeTierTeaser actual) {
        assertPledgeTierTeaserUpdatableFieldsEquals(expected, actual);
        assertPledgeTierTeaserUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPledgeTierTeaserAutoGeneratedPropertiesEquals(PledgeTierTeaser expected, PledgeTierTeaser actual) {
        assertThat(actual)
            .as("Verify PledgeTierTeaser auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPledgeTierTeaserUpdatableFieldsEquals(PledgeTierTeaser expected, PledgeTierTeaser actual) {
        assertThat(actual)
            .as("Verify PledgeTierTeaser relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getBlurb()).as("check blurb").isEqualTo(expected.getBlurb()))
            .satisfies(a ->
                assertThat(a.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getAmount())
            )
            .satisfies(a -> assertThat(a.getCurrency()).as("check currency").isEqualTo(expected.getCurrency()))
            .satisfies(a ->
                assertThat(a.getVoucherValue())
                    .as("check voucherValue")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getVoucherValue())
            )
            .satisfies(a -> assertThat(a.getHandoffUrl()).as("check handoffUrl").isEqualTo(expected.getHandoffUrl()))
            .satisfies(a -> assertThat(a.getDisplayOrder()).as("check displayOrder").isEqualTo(expected.getDisplayOrder()))
            .satisfies(a -> assertThat(a.getPublished()).as("check published").isEqualTo(expected.getPublished()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPledgeTierTeaserUpdatableRelationshipsEquals(PledgeTierTeaser expected, PledgeTierTeaser actual) {
        // empty method
    }
}
