package net.jojoaddison.abofonsa.preview.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ServiceHighlightAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceHighlightAllPropertiesEquals(ServiceHighlight expected, ServiceHighlight actual) {
        assertServiceHighlightAutoGeneratedPropertiesEquals(expected, actual);
        assertServiceHighlightAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceHighlightAllUpdatablePropertiesEquals(ServiceHighlight expected, ServiceHighlight actual) {
        assertServiceHighlightUpdatableFieldsEquals(expected, actual);
        assertServiceHighlightUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceHighlightAutoGeneratedPropertiesEquals(ServiceHighlight expected, ServiceHighlight actual) {
        assertThat(actual)
            .as("Verify ServiceHighlight auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceHighlightUpdatableFieldsEquals(ServiceHighlight expected, ServiceHighlight actual) {
        assertThat(actual)
            .as("Verify ServiceHighlight relevant properties")
            .satisfies(a -> assertThat(a.getLabel()).as("check label").isEqualTo(expected.getLabel()))
            .satisfies(a -> assertThat(a.getDisplayOrder()).as("check displayOrder").isEqualTo(expected.getDisplayOrder()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceHighlightUpdatableRelationshipsEquals(ServiceHighlight expected, ServiceHighlight actual) {
        assertThat(actual)
            .as("Verify ServiceHighlight relationships")
            .satisfies(a -> assertThat(a.getService()).as("check service").isEqualTo(expected.getService()));
    }
}
