package net.jojoaddison.abofonsa.preview.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SocialLinkAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSocialLinkAllPropertiesEquals(SocialLink expected, SocialLink actual) {
        assertSocialLinkAutoGeneratedPropertiesEquals(expected, actual);
        assertSocialLinkAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSocialLinkAllUpdatablePropertiesEquals(SocialLink expected, SocialLink actual) {
        assertSocialLinkUpdatableFieldsEquals(expected, actual);
        assertSocialLinkUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSocialLinkAutoGeneratedPropertiesEquals(SocialLink expected, SocialLink actual) {
        assertThat(actual)
            .as("Verify SocialLink auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSocialLinkUpdatableFieldsEquals(SocialLink expected, SocialLink actual) {
        assertThat(actual)
            .as("Verify SocialLink relevant properties")
            .satisfies(a -> assertThat(a.getPlatform()).as("check platform").isEqualTo(expected.getPlatform()))
            .satisfies(a -> assertThat(a.getLabel()).as("check label").isEqualTo(expected.getLabel()))
            .satisfies(a -> assertThat(a.getUrl()).as("check url").isEqualTo(expected.getUrl()))
            .satisfies(a -> assertThat(a.getIconKey()).as("check iconKey").isEqualTo(expected.getIconKey()))
            .satisfies(a -> assertThat(a.getDisplayOrder()).as("check displayOrder").isEqualTo(expected.getDisplayOrder()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSocialLinkUpdatableRelationshipsEquals(SocialLink expected, SocialLink actual) {
        // empty method
    }
}
