package net.jojoaddison.abofonsa.preview.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class WaitlistSignupAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWaitlistSignupAllPropertiesEquals(WaitlistSignup expected, WaitlistSignup actual) {
        assertWaitlistSignupAutoGeneratedPropertiesEquals(expected, actual);
        assertWaitlistSignupAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWaitlistSignupAllUpdatablePropertiesEquals(WaitlistSignup expected, WaitlistSignup actual) {
        assertWaitlistSignupUpdatableFieldsEquals(expected, actual);
        assertWaitlistSignupUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWaitlistSignupAutoGeneratedPropertiesEquals(WaitlistSignup expected, WaitlistSignup actual) {
        assertThat(actual)
            .as("Verify WaitlistSignup auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWaitlistSignupUpdatableFieldsEquals(WaitlistSignup expected, WaitlistSignup actual) {
        assertThat(actual)
            .as("Verify WaitlistSignup relevant properties")
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getEmailNormalized()).as("check emailNormalized").isEqualTo(expected.getEmailNormalized()))
            .satisfies(a -> assertThat(a.getFullName()).as("check fullName").isEqualTo(expected.getFullName()))
            .satisfies(a -> assertThat(a.getOrganisation()).as("check organisation").isEqualTo(expected.getOrganisation()))
            .satisfies(a -> assertThat(a.getAudience()).as("check audience").isEqualTo(expected.getAudience()))
            .satisfies(a -> assertThat(a.getPlanOfInterest()).as("check planOfInterest").isEqualTo(expected.getPlanOfInterest()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getLocale()).as("check locale").isEqualTo(expected.getLocale()))
            .satisfies(a -> assertThat(a.getSourcePage()).as("check sourcePage").isEqualTo(expected.getSourcePage()))
            .satisfies(a -> assertThat(a.getUtmSource()).as("check utmSource").isEqualTo(expected.getUtmSource()))
            .satisfies(a -> assertThat(a.getUtmMedium()).as("check utmMedium").isEqualTo(expected.getUtmMedium()))
            .satisfies(a -> assertThat(a.getUtmCampaign()).as("check utmCampaign").isEqualTo(expected.getUtmCampaign()))
            .satisfies(a -> assertThat(a.getReferrer()).as("check referrer").isEqualTo(expected.getReferrer()))
            .satisfies(a -> assertThat(a.getDeviceType()).as("check deviceType").isEqualTo(expected.getDeviceType()))
            .satisfies(a -> assertThat(a.getConsentGiven()).as("check consentGiven").isEqualTo(expected.getConsentGiven()))
            .satisfies(a -> assertThat(a.getConfirmationToken()).as("check confirmationToken").isEqualTo(expected.getConfirmationToken()))
            .satisfies(a -> assertThat(a.getConfirmedAt()).as("check confirmedAt").isEqualTo(expected.getConfirmedAt()))
            .satisfies(a -> assertThat(a.getUnsubscribedAt()).as("check unsubscribedAt").isEqualTo(expected.getUnsubscribedAt()))
            .satisfies(a -> assertThat(a.getCapturedAt()).as("check capturedAt").isEqualTo(expected.getCapturedAt()))
            .satisfies(a -> assertThat(a.getIpHash()).as("check ipHash").isEqualTo(expected.getIpHash()))
            .satisfies(a -> assertThat(a.getUserAgent()).as("check userAgent").isEqualTo(expected.getUserAgent()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWaitlistSignupUpdatableRelationshipsEquals(WaitlistSignup expected, WaitlistSignup actual) {
        // empty method
    }
}
